Show error messages
ashalva/ios.memenator pull request #34
Opened 2023-03-11 20:29 UTC by qetiavanashvili

1.  I have added new properties in viewmodel: isLoading & hasError.
2.  I have written if statement for receiving response (receiveCompletion or receiveValue).

https://github.com/ashalva/ios.memenator/issues/2

2023-03-11 20:31 UTC, ashalva requested changes
You have updated the logic only in vm. What about the view ? Based on the properties you have added you need to show specific subviews in your `DogBreedsListView`. Check how `RedditView` uses these properties and try to replicate.

Your goal is to see:
1. loading when request is being sent
2. error when request fails

2023-03-11 20:51 UTC, qetiavanashvili commented
I thought it just needed in vm. I'll see and try to fix it...

2023-03-15 09:29 UTC, ashalva commented on GeorgianMemenator/Scenes/DogBreedsList/DogBreedsListView.swift
> +                Text("Is loading")
No need to show text here. Just `ActivityIndicator` is enough

2023-03-15 10:45 UTC, qetiavanashvili commented on GeorgianMemenator/Scenes/DogBreedsList/DogBreedsListView.swift
> +                Text("Is loading")
I just liked the text and that's why I did it...

2023-03-15 10:46 UTC, qetiavanashvili commented on GeorgianMemenator/Scenes/DogBreedsList/DogBreedsListView.swift
> +                Text("Is loading")
I pushed the latest version, if everything is correct, I'll merge

2023-03-15 12:08 UTC, ashalva approved these changes
Looking good!

2023-03-15 19:38 UTC, merged